EM_MODE = 0
HardCutEM_MODE = 1
RPCL_MODE = 2
BYY_TWO_ALTERNATION_STEP_MODE = 3
LAGRANGE_YING_YANG_ALTERNATION_MODE = 4

FORCE_TRIMMING = 11
SOFT_TRIMMING = 12

SPECTRAL_CLUSTERING_ELISION = 21
SPECTRAL_CLUSTERING_KNN = 22
SPECTRAL_CLUSTERING_MUTUAL_KNN = 23

SPECTRAL_CLUSTERING_NOT_REGULAR_W = 24
SPECTRAL_CLUSTERING_RANDOM_W = 25
SPECTRAL_CLUSTERING_SYMMETRY_W = 26

DBSCAN_NOISE_POINT = 30
DBSCAN_UNCLASSIFIED = 31



